### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by dovf**

### CODE REVIEW

**Comment by BinyaminSharet** [comment]
@dovf the calculation in 31bd6e1 seems too unpredicted to me. There's no relation between the count and the delay time, and the count always changes. I think that it should be based solely on time, regardless of the count. What do you think?

**Comment by dovf** [comment]
I agree that the throttling should be time-based. That's precisely why I did the calculation: if we're sleeping for `self.victim_alive_check_delay` seconds each time around the loop, then after `10/self.victim_alive_check_delay` times roughly 10 seconds should have passed. Am I missing something?

**Comment by dovf** [comment]
But there is a division-by-zero issue here -- oops!

**Comment by BinyaminSharet** [comment]
I missed the division by zero :) Regarding my original comment, I think you are right, but it's not that clear from the code, and I think there could be problems. If we want to print every 10 secs. or so - we should simply use time.time() to check the time IMO.

**Comment by dovf** [comment]
Agree. I'll push a revised change.

**Comment by dovf** [comment]
Fixed as discussed.

**Pull request merged**
