### PR TITLE
[docs] fix typos in server_fuzzing.rst

### PR DESCRIPTION
**Pull request by navhaxs**
Corrected the example snippets to use the correct names in super() to match the class name, and also added the missing super call in "pre_test"

### CODE REVIEW

**Comment by BinyaminSharet** [comment]
@navhaxs thanks for the PR! Really appreciated. Could you please re-submit it to the next branch?

**Comment by BinyaminSharet** [comment]
@navhaxs Changing the pull request target branch should be easy now, see here: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by navhaxs** [comment]
Sure, very easy :+1:

**Comment by navhaxs** [comment]
Apologies, I've corrected that. Also noticed and fixed another typo.

**Comment by BinyaminSharet** [comment]
Thanks. Merged.

**Pull request merged**
