### PR TITLE
Fix division for compability Python3

### PR DESCRIPTION
**Pull request by GH0st3rs**

### CODE REVIEW

**Comment by BinyaminSharet** [comment]
Do you mind performing the fixes to the other pull request first? just so we'll be in a stable state there before moving on. currently the tests can even really begin.

**Comment by GH0st3rs** [comment]
well, however it is a complex change. In addition to the encoder, it is tedious to change the fields and all the places where there is interaction with them. I would suggest changes be made in stages. Immediately fix everything will be very difficult. And I'm not sure that it will work as it should

**Comment by GH0st3rs** [comment]
I suggest first starting with:
1. encoder 
2. fields 
3. tests 
4. reporting - json does not allow to save raw data
5. etc

**Comment by BinyaminSharet** [comment]
Sorry, I'm not available to deal with this most of the time. Do you mind continuing the conversation in [our gitter channel](https://gitter.im/cisco-sas/kitty)?

**Pull request merged**
